["protostar.config"]
protostar_version = "0.6.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
main = [
    "src/main.cairo",
]

["protostar.test"]
cairo-path = ["./lib/cairo_contracts/src"]

["protostar.build"]
cairo-path = ["./lib/cairo_contracts/src"]
